name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run HTMLHint (if index.html exists)
        run: |
          if [ -f index.html ]; then
            npx htmlhint index.html || true
          else
            echo "index.html not found, skipping HTMLHint."
          fi

      - name: Run ESLint (if script.js exists)
        run: |
          if [ -f script.js ]; then
            npx eslint script.js --no-error-on-unmatched-pattern || true
          else
            echo "script.js not found, skipping ESLint."
          fi

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./

